services:
  postgres:
    image: postgres:15
    container_name: central_database
    restart: always
    env_file:
      - .env
    environment:
      TZ: "${TZ}"
    ports:
      - "8000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: >
      postgres -c listen_addresses='*' -c hba_file=/etc/postgresql/pg_hba.conf

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "8001:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
